QBCore.Shared.Items = {
    -- WEAPONS
    -- Melee
    weapon_unarmed               = { name = 'weapon_unarmed', label = '素手', weight = 1000, type = 'weapon', ammotype = nil, image = 'placeholder.png', unique = true, useable = false, description = 'こぶしで語ろう' },
    weapon_dagger                = { name = 'weapon_dagger', label = 'ダガー', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_dagger.png', unique = true, useable = false, description = '先端が尖った刃を持つ短いナイフ。武器として使用される' },
    weapon_bat                   = { name = 'weapon_bat', label = 'バット', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_bat.png', unique = true, useable = false, description = 'スポーツでボールを打つために使用される (または他のもの)' },
    weapon_bottle                = { name = 'weapon_bottle', label = '割れたボトル', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_bottle.png', unique = true, useable = false, description = '割れたボトル' },
    weapon_crowbar               = { name = 'weapon_crowbar', label = 'バール', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_crowbar.png', unique = true, useable = false, description = 'てこ棒として使われる、平らな端を持つ鉄の棒' },
    weapon_flashlight            = { name = 'weapon_flashlight', label = '懐中電灯', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_flashlight.png', unique = true, useable = false, description = '電池で動く携帯用のライト' },
    weapon_golfclub              = { name = 'weapon_golfclub', label = 'ゴルフクラブ', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_golfclub.png', unique = true, useable = false, description = 'ゴルフでボールを打つために使用されるクラブ' },
    weapon_hammer                = { name = 'weapon_hammer', label = 'ハンマー', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_hammer.png', unique = true, useable = false, description = '物を壊したり（脚を折ったり）、釘を打ち込んだりする作業に使用される' },
    weapon_hatchet               = { name = 'weapon_hatchet', label = '手斧', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_hatchet.png', unique = true, useable = false, description = '片手で使うための短い柄の小さな斧' },
    weapon_knuckle               = { name = 'weapon_knuckle', label = 'メリケンサック', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_knuckle.png', unique = true, useable = false, description = '打撃の効果を高めるために、格闘時に指関節に装着する金属製のガード' },
    weapon_knife                 = { name = 'weapon_knife', label = 'ナイフ', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_knife.png', unique = true, useable = false, description = '刃が柄に取り付けられた道具。切断用または武器として使用される' },
    weapon_machete               = { name = 'weapon_machete', label = 'マチェーテ', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_machete.png', unique = true, useable = false, description = '武器として使用される幅広で重いナイフ' },
    weapon_switchblade           = { name = 'weapon_switchblade', label = 'スウィッチブレード', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_switchblade.png', unique = true, useable = false, description = 'ボタンを押すと柄から刃が飛び出すナイフ' },
    weapon_nightstick            = { name = 'weapon_nightstick', label = '警棒', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_nightstick.png', unique = true, useable = false, description = '警察官の警棒' },
    weapon_wrench                = { name = 'weapon_wrench', label = 'レンチ', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_wrench.png', unique = true, useable = false, description = 'ナット、ボルト、パイプなどを掴んで回すための工具' },
    weapon_battleaxe             = { name = 'weapon_battleaxe', label = 'バトルアックス', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_battleaxe.png', unique = true, useable = false, description = '古代の戦争で使用された、幅広で大きな刃を持つ斧' },
    weapon_poolcue               = { name = 'weapon_poolcue', label = 'プールキュー', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_poolcue.png', unique = true, useable = false, description = 'ボールを打つために使用される棒。通常は手玉を打つ (または他のもの)' },
    weapon_briefcase             = { name = 'weapon_briefcase', label = 'ブリーフケース', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_briefcase.png', unique = true, useable = false, description = '重要な書類を保管するためのブリーフケース' },
    weapon_briefcase_02          = { name = 'weapon_briefcase_02', label = 'スーツケース', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_briefcase2.png', unique = true, useable = false, description = 'リバティーシティへの素敵な休暇に最適' },
    weapon_garbagebag            = { name = 'weapon_garbagebag', label = 'ゴミ袋', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_garbagebag.png', unique = true, useable = false, description = 'ゴミ袋' },
    weapon_handcuffs             = { name = 'weapon_handcuffs', label = '手錠', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_handcuffs.png', unique = true, useable = false, description = '囚人の手首を拘束するための、ロック可能な連結された金属の輪' },
    weapon_bread                 = { name = 'weapon_bread', label = 'バゲット', weight = 1000, type = 'weapon', ammotype = nil, image = 'baquette.png', unique = true, useable = false, description = 'パン...？' },
    weapon_stone_hatchet         = { name = 'weapon_stone_hatchet', label = '石斧', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_stone_hatchet.png', unique = true, useable = true, description = '石斧' },
    weapon_candycane             = { name = 'weapon_candycane', label = 'キャンディーケイン', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_candycane', unique = true, useable = true, description = 'キャンディーケイン' },

    -- ハンドガン
    weapon_pistol                = { name = 'weapon_pistol', label = 'ワルサー P99', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_pistol.png', unique = true, useable = false, description = '片手で持つように設計された小型の銃器' },
    weapon_pistol_mk2            = { name = 'weapon_pistol_mk2', label = 'ピストル Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_pistol_mk2.png', unique = true, useable = false, description = 'アップグレードされた、片手で持つように設計された小型の銃器' },
    weapon_combatpistol          = { name = 'weapon_combatpistol', label = 'コンバットピストル', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_combatpistol.png', unique = true, useable = false, description = '片手で持つように設計された戦闘用小型銃器' },
    weapon_appistol              = { name = 'weapon_appistol', label = 'APピストル', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_appistol.png', unique = true, useable = false, description = '片手で持つように設計された自動式の小型銃器' },
    weapon_stungun               = { name = 'weapon_stungun', label = 'スタンガン', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_stungun.png', unique = true, useable = false, description = 'ワイヤーでバッテリーに接続されたダーツを発射し、一時的な麻痺を引き起こす武器' },
    weapon_pistol50              = { name = 'weapon_pistol50', label = 'ピストル.50', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_pistol50.png', unique = true, useable = false, description = '両手で持つように設計された.50口径の銃器' },
    weapon_snspistol             = { name = 'weapon_snspistol', label = 'SNSピストル', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_snspistol.png', unique = true, useable = false, description = '簡単に隠せるように設計された非常に小さな銃器' },
    weapon_heavypistol           = { name = 'weapon_heavypistol', label = 'ヘビーピストル', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_heavypistol.png', unique = true, useable = false, description = '片手で持つように設計された（あるいは試みられた）ずっしりとした銃器' },
    weapon_vintagepistol         = { name = 'weapon_vintagepistol', label = 'ビンテージピストル', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_vintagepistol.png', unique = true, useable = false, description = '片手で持つように設計されたアンティークの銃器' },
    weapon_flaregun              = { name = 'weapon_flaregun', label = 'フレアガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_FLARE', image = 'weapon_flaregun.png', unique = true, useable = false, description = '信号弾を発射するためのハンドガン' },
    weapon_marksmanpistol        = { name = 'weapon_marksmanpistol', label = 'マークスマンピストル', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_marksmanpistol.png', unique = true, useable = false, description = '片手で持つように設計された、非常に精密な小型銃器' },
    weapon_revolver              = { name = 'weapon_revolver', label = 'リボルバー', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_revolver.png', unique = true, useable = false, description = 'リロードせずに数発発射できる回転式弾倉を備えたピストル' },
    weapon_revolver_mk2          = { name = 'weapon_revolver_mk2', label = 'バイオレンス', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_revolver_mk2.png', unique = true, useable = true, description = 'バイオレンスだ' },
    weapon_doubleaction          = { name = 'weapon_doubleaction', label = 'ダブルアクションリボルバー', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_doubleaction.png', unique = true, useable = true, description = 'ダブルアクションリボルバー' },
    weapon_snspistol_mk2         = { name = 'weapon_snspistol_mk2', label = 'SNSピストル Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_snspistol_mk2.png', unique = true, useable = true, description = 'SNSピストル MK2' },
    weapon_raypistol             = { name = 'weapon_raypistol', label = 'アップンアトマイザー', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_raypistol.png', unique = true, useable = true, description = '武器 レーザーピストル' },
    weapon_ceramicpistol         = { name = 'weapon_ceramicpistol', label = 'セラミックピストル', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_ceramicpistol.png', unique = true, useable = true, description = '武器 セラミックピストル' },
    weapon_navyrevolver          = { name = 'weapon_navyrevolver', label = 'ネイビーリボルバー', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_navyrevolver.png', unique = true, useable = true, description = '武器 ネイビーリボルバー' },
    weapon_gadgetpistol          = { name = 'weapon_gadgetpistol', label = 'ペリコピストル', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_gadgetpistol.png', unique = true, useable = true, description = '武器 ガジェットピストル' },
    weapon_pistolxm3             = { name = 'weapon_pistolxm3', label = 'ピストル XM3', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_pistolxm3.png', unique = true, useable = true, description = 'ピストル XM3' },
    -- サブマシンガン
    weapon_microsmg              = { name = 'weapon_microsmg', label = 'マイクロSMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_microsmg.png', unique = true, useable = false, description = '手持ちの軽量機関銃' },
    weapon_smg                   = { name = 'weapon_smg', label = 'SMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_smg.png', unique = true, useable = false, description = '手持ちの軽量機関銃' },
    weapon_smg_mk2               = { name = 'weapon_smg_mk2', label = 'SMG Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_smg_mk2.png', unique = true, useable = true, description = 'SMG MK2' },
    weapon_assaultsmg            = { name = 'weapon_assaultsmg', label = 'アサルトSMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_assaultsmg.png', unique = true, useable = false, description = '手持ちの軽量機関銃のアサルトバージョン' },
    weapon_combatpdw             = { name = 'weapon_combatpdw', label = 'コンバットPDW', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_combatpdw.png', unique = true, useable = false, description = '手持ちの軽量機関銃のコンバットバージョン' },
    weapon_machinepistol         = { name = 'weapon_machinepistol', label = 'テック9', weight = 1000, type = 'weapon', ammotype = 'AMMO_PISTOL', image = 'weapon_machinepistol.png', unique = true, useable = false, description = 'バースト射撃またはフルオート射撃が可能な自動装填式ピストル' },
    weapon_minismg               = { name = 'weapon_minismg', label = 'ミニSMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_minismg.png', unique = true, useable = false, description = 'ミニサイズの手持ち軽量機関銃' },
    weapon_raycarbine            = { name = 'weapon_raycarbine', label = 'アンホーリーヘルブリンガー', weight = 1000, type = 'weapon', ammotype = 'AMMO_SMG', image = 'weapon_raycarbine.png', unique = true, useable = true, description = '武器 レーザーカービン' },

    -- ショットガン
    weapon_pumpshotgun           = { name = 'weapon_pumpshotgun', label = 'ポンプ式ショットガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_pumpshotgun.png', unique = true, useable = false, description = '近距離で散弾を発射するポンプアクション式滑腔銃' },
    weapon_sawnoffshotgun        = { name = 'weapon_sawnoffshotgun', label = 'ソウドオフショットガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_sawnoffshotgun.png', unique = true, useable = false, description = '近距離で散弾を発射する銃身を切り詰めた滑腔銃' },
    weapon_assaultshotgun        = { name = 'weapon_assaultshotgun', label = 'アサルトショットガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_assaultshotgun.png', unique = true, useable = false, description = '近距離で散弾を発射する滑腔銃のアサルトバージョン' },
    weapon_bullpupshotgun        = { name = 'weapon_bullpupshotgun', label = 'ブルパップショットガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_bullpupshotgun.png', unique = true, useable = false, description = '近距離で散弾を発射するコンパクトな滑腔銃' },
    weapon_musket                = { name = 'weapon_musket', label = 'マスケット銃', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_musket.png', unique = true, useable = false, description = '歩兵の軽銃。長い銃身を持ち、通常は滑腔、前装式で、肩から発射される' },
    weapon_heavyshotgun          = { name = 'weapon_heavyshotgun', label = 'ヘビーショットガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_heavyshotgun.png', unique = true, useable = false, description = '近距離で散弾を発射する大型の滑腔銃' },
    weapon_dbshotgun             = { name = 'weapon_dbshotgun', label = 'ダブルバレルショットガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_dbshotgun.png', unique = true, useable = false, description = '2本の並列した銃身を持つショットガン。2発の単発を素早く連続して発射できる' },
    weapon_autoshotgun           = { name = 'weapon_autoshotgun', label = 'オートショットガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_autoshotgun.png', unique = true, useable = false, description = '連続した高速射撃が可能なショットガン' },
    weapon_pumpshotgun_mk2       = { name = 'weapon_pumpshotgun_mk2', label = 'ポンプ式ショットガン Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_pumpshotgun_mk2.png', unique = true, useable = true, description = 'ポンプ式ショットガン MK2' },
    weapon_combatshotgun         = { name = 'weapon_combatshotgun', label = 'コンバットショットガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_SHOTGUN', image = 'weapon_combatshotgun.png', unique = true, useable = true, description = '武器 コンバットショットガン' },

    -- アサルトライフル
    weapon_assaultrifle          = { name = 'weapon_assaultrifle', label = 'アサルトライフル', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_assaultrifle.png', unique = true, useable = false, description = '歩兵用として設計された、連射可能で弾倉式の自動小銃' },
    weapon_assaultrifle_mk2      = { name = 'weapon_assaultrifle_mk2', label = 'アサルトライフル Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_assaultrifle_mk2.png', unique = true, useable = true, description = 'アサルトライフル MK2' },
    weapon_carbinerifle          = { name = 'weapon_carbinerifle', label = 'カービンライフル', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_carbinerifle.png', unique = true, useable = false, description = '軽量な自動小銃' },
    weapon_carbinerifle_mk2      = { name = 'weapon_carbinerifle_mk2', label = 'カービンライフル Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_carbinerifle_mk2.png', unique = true, useable = true, description = 'カービンライフル MK2' },
    weapon_advancedrifle         = { name = 'weapon_advancedrifle', label = 'アドバンスライフル', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_advancedrifle.png', unique = true, useable = false, description = '歩兵用として設計された、連射可能で弾倉式の自動小銃のアサルトバージョン' },
    weapon_specialcarbine        = { name = 'weapon_specialcarbine', label = 'スペシャルカービン', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_specialcarbine.png', unique = true, useable = false, description = 'あらゆる戦闘状況に対応できる非常に汎用性の高いアサルトライフル' },
    weapon_bullpuprifle          = { name = 'weapon_bullpuprifle', label = 'ブルパップライフル', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_bullpuprifle.png', unique = true, useable = false, description = 'コンパクトな自動アサルトライフル' },
    weapon_compactrifle          = { name = 'weapon_compactrifle', label = 'コンパクトライフル', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_compactrifle.png', unique = true, useable = false, description = 'アサルトライフルのコンパクトバージョン' },
    weapon_specialcarbine_mk2    = { name = 'weapon_specialcarbine_mk2', label = 'スペシャルカービン Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_specialcarbine_mk2.png', unique = true, useable = true, description = '武器 スペシャルカービン MK2' },
    weapon_bullpuprifle_mk2      = { name = 'weapon_bullpuprifle_mk2', label = 'ブルパップライフル Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_bullpuprifle_mk2.png', unique = true, useable = true, description = 'ブルパップライフル MK2' },
    weapon_militaryrifle         = { name = 'weapon_militaryrifle', label = 'ミリタリーライフル', weight = 1000, type = 'weapon', ammotype = 'AMMO_RIFLE', image = 'weapon_militaryrifle.png', unique = true, useable = true, description = '武器 ミリタリーライフル' },

    -- ライトマシンガン
    weapon_mg                    = { name = 'weapon_mg', label = 'マシンガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', image = 'weapon_mg.png', unique = true, useable = false, description = '引き金を引いている間、弾丸を素早く連続して発射する自動銃' },
    weapon_combatmg              = { name = 'weapon_combatmg', label = 'コンバットMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', image = 'weapon_combatmg.png', unique = true, useable = false, description = '引き金を引いている間、弾丸を素早く連続して発射する自動銃のコンバットバージョン' },
    weapon_gusenberg             = { name = 'weapon_gusenberg', label = 'トンプソンSMG', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', image = 'weapon_gusenberg.png', unique = true, useable = false, description = 'トミーガンとして一般的に知られている自動小銃' },
    weapon_combatmg_mk2          = { name = 'weapon_combatmg_mk2', label = 'コンバットMG Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_MG', image = 'weapon_combatmg_mk2.png', unique = true, useable = true, description = '武器 コンバットMG MK2' },

    -- スナイパーライフル
    weapon_sniperrifle           = { name = 'weapon_sniperrifle', label = 'スナイパーライフル', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_sniperrifle.png', unique = true, useable = false, description = '高精度な長距離ライフル' },
    weapon_heavysniper           = { name = 'weapon_heavysniper', label = 'ヘビースナイパー', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_heavysniper.png', unique = true, useable = false, description = 'アップグレードされた高精度な長距離ライフル' },
    weapon_marksmanrifle         = { name = 'weapon_marksmanrifle', label = 'マークスマンライフル', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_marksmanrifle.png', unique = true, useable = false, description = '非常に正確な単発ライフル' },
    weapon_remotesniper          = { name = 'weapon_remotesniper', label = 'リモートスナイパー', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER_REMOTE', image = 'weapon_remotesniper.png', unique = true, useable = false, description = '携帯可能な高精度な長距離ライフル' },
    weapon_heavysniper_mk2       = { name = 'weapon_heavysniper_mk2', label = 'ヘビースナイパー Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_heavysniper_mk2.png', unique = true, useable = true, description = '武器 ヘビースナイパー MK2' },
    weapon_marksmanrifle_mk2     = { name = 'weapon_marksmanrifle_mk2', label = 'マークスマンライフル Mk II', weight = 1000, type = 'weapon', ammotype = 'AMMO_SNIPER', image = 'weapon_marksmanrifle_mk2.png', unique = true, useable = true, description = '武器 マークスマンライフル MK2' },

    -- 重火器
    weapon_rpg                   = { name = 'weapon_rpg', label = 'RPG', weight = 1000, type = 'weapon', ammotype = 'AMMO_RPG', image = 'weapon_rpg.png', unique = true, useable = false, description = 'ロケット推進式グレネードランチャー' },
    weapon_grenadelauncher       = { name = 'weapon_grenadelauncher', label = 'グレネードランチャー', weight = 1000, type = 'weapon', ammotype = 'AMMO_GRENADELAUNCHER', image = 'weapon_grenadelauncher.png', unique = true, useable = false, description = '特別に設計された大口径の弾を発射する武器。多くの場合、爆発、煙、またはガスの弾頭を持つ' },
    weapon_grenadelauncher_smoke = { name = 'weapon_grenadelauncher_smoke', label = '煙グレネードランチャー', weight = 1000, type = 'weapon', ammotype = 'AMMO_GRENADELAUNCHER', image = 'weapon_smokegrenade.png', unique = true, useable = false, description = '爆発すると大量の煙を発生させる弾' },
    weapon_minigun               = { name = 'weapon_minigun', label = 'ミニガン', weight = 1000, type = 'weapon', ammotype = 'AMMO_MINIGUN', image = 'weapon_minigun.png', unique = true, useable = false, description = '6本の銃身が回転する携帯式機関銃。毎分最大6,000発の発射速度で射撃可能' },
    weapon_firework              = { name = 'weapon_firework', label = '花火ランチャー', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_firework.png', unique = true, useable = false, description = '火薬やその他の可燃性化学物質を含む装置。着火すると壮観な爆発を引き起こす' },
    weapon_railgun               = { name = 'weapon_railgun', label = 'レールガン', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_railgun.png', unique = true, useable = false, description = '電磁力を使用して高速の弾丸を発射する武器' },
    weapon_railgunxm3            = { name = 'weapon_railgunxm3', label = 'レールガン XM3', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_railgunxm3.png', unique = true, useable = false, description = '電磁力を使用して高速の弾丸を発射する武器' },
    weapon_hominglauncher        = { name = 'weapon_hominglauncher', label = 'ホーミングランチャー', weight = 1000, type = 'weapon', ammotype = 'AMMO_STINGER', image = 'weapon_hominglauncher.png', unique = true, useable = false, description = '電子装置を搭載し、ターゲットを見つけて命中させることができる武器' },
    weapon_compactlauncher       = { name = 'weapon_compactlauncher', label = 'コンパクトランチャー', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_compactlauncher.png', unique = true, useable = false, description = 'コンパクトなグレネードランチャー' },
    weapon_rayminigun            = { name = 'weapon_rayminigun', label = 'ウィドウメーカー', weight = 1000, type = 'weapon', ammotype = 'AMMO_MINIGUN', image = 'weapon_rayminigun.png', unique = true, useable = true, description = '武器 レーザーミニガン' },

    -- 投擲武器
    weapon_grenade               = { name = 'weapon_grenade', label = 'グレネード', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_grenade.png', unique = true, useable = false, description = '手で投げる爆弾' },
    weapon_bzgas                 = { name = 'weapon_bzgas', label = 'BZガス', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_bzgas.png', unique = true, useable = false, description = '激痛を引き起こすガスの入った容器' },
    weapon_molotov               = { name = 'weapon_molotov', label = '火炎瓶', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_molotov.png', unique = true, useable = false, description = '可燃性の液体で満たされ、点火用の芯が付いたボトル製の粗製の爆弾' },
    weapon_stickybomb            = { name = 'weapon_stickybomb', label = 'C4', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_stickybomb.png', unique = true, useable = false, description = '接着剤で覆われた爆薬。投げると物体に貼りつき、爆発するまでくっついている' },
    weapon_proxmine              = { name = 'weapon_proxmine', label = '近接マイン', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_proximitymine.png', unique = true, useable = false, description = '地面に設置され、近くを通ると爆発する爆弾' },
    weapon_snowball              = { name = 'weapon_snowball', label = '雪玉', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_snowball.png', unique = true, useable = false, description = '固めた雪の玉。特に他の人に投げて楽しむために作られたもの' },
    weapon_pipebomb              = { name = 'weapon_pipebomb', label = 'パイプ爆弾', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_pipebomb.png', unique = true, useable = false, description = 'パイプの中に部品が収められた手製の爆弾' },
    weapon_ball                  = { name = 'weapon_ball', label = 'ボール', weight = 1000, type = 'weapon', ammotype = 'AMMO_BALL', image = 'weapon_ball.png', unique = true, useable = false, description = 'ゲームで蹴ったり、投げたり、打ったりする、中身が詰まった、または中空の球形または卵形の物体' },
    weapon_smokegrenade          = { name = 'weapon_smokegrenade', label = '煙グレネード', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_c4.png', unique = true, useable = false, description = '遠隔で起爆できる爆薬' },
    weapon_flare                 = { name = 'weapon_flare', label = 'フレアピストル', weight = 1000, type = 'weapon', ammotype = 'AMMO_FLARE', image = 'weapon_flare.png', unique = true, useable = false, description = '照明や信号用に使用される小さな火工品' },

    -- その他
    weapon_petrolcan             = { name = 'weapon_petrolcan', label = 'ガソリン缶', weight = 1000, type = 'weapon', ammotype = 'AMMO_PETROLCAN', image = 'weapon_petrolcan.png', unique = true, useable = false, description = 'プレス鋼製の頑丈な液体容器' },
    weapon_fireextinguisher      = { name = 'weapon_fireextinguisher', label = '消火器', weight = 1000, type = 'weapon', ammotype = nil, image = 'weapon_fireextinguisher.png', unique = true, useable = false, description = '水、泡、ガス、その他の物質の噴流を放出して火を消す携帯用装置' },
    weapon_hazardcan             = { name = 'weapon_hazardcan', label = '有害ガソリン缶', weight = 1000, type = 'weapon', ammotype = 'AMMO_PETROLCAN', image = 'weapon_hazardcan.png', unique = true, useable = true, description = '武器 ハザードガソリン缶' },

    -- 武器アタッチメント
    clip_attachment              = { name = 'clip_attachment', label = 'マガジン', weight = 1000, type = 'item', image = 'clip_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用マガジン' },
    drum_attachment              = { name = 'drum_attachment', label = 'ドラムマガジン', weight = 1000, type = 'item', image = 'drum_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用ドラムマガジン' },
    flashlight_attachment        = { name = 'flashlight_attachment', label = 'フラッシュライト', weight = 1000, type = 'item', image = 'flashlight_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用フラッシュライト' },
    suppressor_attachment        = { name = 'suppressor_attachment', label = 'サプレッサー', weight = 1000, type = 'item', image = 'suppressor_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用サプレッサー' },
    smallscope_attachment        = { name = 'smallscope_attachment', label = '小型スコープ', weight = 1000, type = 'item', image = 'smallscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用小型スコープ' },
    medscope_attachment          = { name = 'medscope_attachment', label = '中型スコープ', weight = 1000, type = 'item', image = 'medscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用中型スコープ' },
    largescope_attachment        = { name = 'largescope_attachment', label = '大型スコープ', weight = 1000, type = 'item', image = 'largescope_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用大型スコープ' },
    holoscope_attachment         = { name = 'holoscope_attachment', label = 'ホロスコープ', weight = 1000, type = 'item', image = 'holoscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用ホロスコープ' },
    advscope_attachment          = { name = 'advscope_attachment', label = '先進スコープ', weight = 1000, type = 'item', image = 'advscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用先進スコープ' },
    nvscope_attachment           = { name = 'nvscope_attachment', label = '暗視スコープ', weight = 1000, type = 'item', image = 'nvscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用暗視スコープ' },
    thermalscope_attachment      = { name = 'thermalscope_attachment', label = 'サーマルスコープ', weight = 1000, type = 'item', image = 'thermalscope_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用サーマルスコープ' },
    flat_muzzle_brake            = { name = 'flat_muzzle_brake', label = 'フラットマズルブレーキ', weight = 1000, type = 'item', image = 'flat_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '武器用マズルブレーキ' },
    tactical_muzzle_brake        = { name = 'tactical_muzzle_brake', label = 'タクティカルマズルブレーキ', weight = 1000, type = 'item', image = 'tactical_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '武器用マズルブレーキ' },
    fat_end_muzzle_brake         = { name = 'fat_end_muzzle_brake', label = 'ファットエンドマズルブレーキ', weight = 1000, type = 'item', image = 'fat_end_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '武器用マズルブレーキ' },
    precision_muzzle_brake       = { name = 'precision_muzzle_brake', label = '精密マズルブレーキ', weight = 1000, type = 'item', image = 'precision_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '武器用マズルブレーキ' },
    heavy_duty_muzzle_brake      = { name = 'heavy_duty_muzzle_brake', label = 'HDマズルブレーキ', weight = 1000, type = 'item', image = 'heavy_duty_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '武器用マズルブレーキ' },
    slanted_muzzle_brake         = { name = 'slanted_muzzle_brake', label = 'スラントマズルブレーキ', weight = 1000, type = 'item', image = 'slanted_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '武器用マズルブレーキ' },
    split_end_muzzle_brake       = { name = 'split_end_muzzle_brake', label = 'スプリットエンドマズルブレーキ', weight = 1000, type = 'item', image = 'split_end_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '武器用マズルブレーキ' },
    squared_muzzle_brake         = { name = 'squared_muzzle_brake', label = 'スクエアマズルブレーキ', weight = 1000, type = 'item', image = 'squared_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '武器用マズルブレーキ' },
    bellend_muzzle_brake         = { name = 'bellend_muzzle_brake', label = 'ベルエンドマズルブレーキ', weight = 1000, type = 'item', image = 'bellend_muzzle_brake.png', unique = false, useable = true, shouldClose = true, description = '武器用マズルブレーキ' },
    barrel_attachment            = { name = 'barrel_attachment', label = 'バレル', weight = 1000, type = 'item', image = 'barrel_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用バレル' },
    grip_attachment              = { name = 'grip_attachment', label = 'グリップ', weight = 1000, type = 'item', image = 'grip_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用グリップ' },
    comp_attachment              = { name = 'comp_attachment', label = 'コンペンセイター', weight = 1000, type = 'item', image = 'comp_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用コンペンセイター' },
    luxuryfinish_attachment      = { name = 'luxuryfinish_attachment', label = '豪華仕上げ', weight = 1000, type = 'item', image = 'luxuryfinish_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用豪華仕上げ' },
    digicamo_attachment          = { name = 'digicamo_attachment', label = 'デジタル迷彩', weight = 1000, type = 'item', image = 'digicamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用デジタル迷彩' },
    brushcamo_attachment         = { name = 'brushcamo_attachment', label = 'ブラッシュ迷彩', weight = 1000, type = 'item', image = 'brushcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用ブラッシュ迷彩' },
    woodcamo_attachment          = { name = 'woodcamo_attachment', label = 'ウッドランド迷彩', weight = 1000, type = 'item', image = 'woodcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用ウッドランド迷彩' },
    skullcamo_attachment         = { name = 'skullcamo_attachment', label = 'スカル迷彩', weight = 1000, type = 'item', image = 'skullcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用スカル迷彩' },
    sessantacamo_attachment      = { name = 'sessantacamo_attachment', label = 'セッサンタノーヴェ迷彩', weight = 1000, type = 'item', image = 'sessantacamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用セッサンタノーヴェ迷彩' },
    perseuscamo_attachment       = { name = 'perseuscamo_attachment', label = 'ペルセウス迷彩', weight = 1000, type = 'item', image = 'perseuscamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用ペルセウス迷彩' },
    leopardcamo_attachment       = { name = 'leopardcamo_attachment', label = 'ヒョウ柄迷彩', weight = 1000, type = 'item', image = 'leopardcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用ヒョウ柄迷彩' },
    zebracamo_attachment         = { name = 'zebracamo_attachment', label = 'ゼブラ迷彩', weight = 1000, type = 'item', image = 'zebracamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用ゼブラ迷彩' },
    geocamo_attachment           = { name = 'geocamo_attachment', label = '幾何学迷彩', weight = 1000, type = 'item', image = 'geocamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用幾何学迷彩' },
    boomcamo_attachment          = { name = 'boomcamo_attachment', label = 'ブーム迷彩', weight = 1000, type = 'item', image = 'boomcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用ブーム迷彩' },
    patriotcamo_attachment       = { name = 'patriotcamo_attachment', label = 'パトリオット迷彩', weight = 1000, type = 'item', image = 'patriotcamo_attachment.png', unique = false, useable = true, shouldClose = true, description = '武器用パトリオット迷彩' },

    -- 武器の色
    weapontint_0                 = { name = 'weapontint_0', label = 'デフォルト色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'デフォルト/黒色の武器色' },
    weapontint_1                 = { name = 'weapontint_1', label = '緑色', weight = 1000, type = 'item', image = 'weapontint_green.png', unique = false, useable = true, shouldClose = true, description = '緑色の武器色' },
    weapontint_2                 = { name = 'weapontint_2', label = '金色', weight = 1000, type = 'item', image = 'weapontint_gold.png', unique = false, useable = true, shouldClose = true, description = '金色の武器色' },
    weapontint_3                 = { name = 'weapontint_3', label = 'ピンク色', weight = 1000, type = 'item', image = 'weapontint_pink.png', unique = false, useable = true, shouldClose = true, description = 'ピンク色の武器色' },
    weapontint_4                 = { name = 'weapontint_4', label = 'アーミー色', weight = 1000, type = 'item', image = 'weapontint_army.png', unique = false, useable = true, shouldClose = true, description = 'アーミーカラーの武器色' },
    weapontint_5                 = { name = 'weapontint_5', label = 'LSPD色', weight = 1000, type = 'item', image = 'weapontint_lspd.png', unique = false, useable = true, shouldClose = true, description = 'LSPDの武器色' },
    weapontint_6                 = { name = 'weapontint_6', label = 'オレンジ色', weight = 1000, type = 'item', image = 'weapontint_orange.png', unique = false, useable = true, shouldClose = true, description = 'オレンジ色の武器色' },
    weapontint_7                 = { name = 'weapontint_7', label = 'プラチナ色', weight = 1000, type = 'item', image = 'weapontint_plat.png', unique = false, useable = true, shouldClose = true, description = 'プラチナ色の武器色' },
    weapontint_mk2_0             = { name = 'weapontint_mk2_0', label = 'クラシックブラック色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用クラシックブラック色' },
    weapontint_mk2_1             = { name = 'weapontint_mk2_1', label = 'クラシックグレー色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用クラシックグレー色' },
    weapontint_mk2_2             = { name = 'weapontint_mk2_2', label = 'クラシックツートン色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用クラシックツートン色' },
    weapontint_mk2_3             = { name = 'weapontint_mk2_3', label = 'クラシックホワイト色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用クラシックホワイト色' },
    weapontint_mk2_4             = { name = 'weapontint_mk2_4', label = 'クラシックベージュ色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用クラシックベージュ色' },
    weapontint_mk2_5             = { name = 'weapontint_mk2_5', label = 'クラシックグリーン色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用クラシックグリーン色' },
    weapontint_mk2_6             = { name = 'weapontint_mk2_6', label = 'クラシックブルー色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用クラシックブルー色' },
    weapontint_mk2_7             = { name = 'weapontint_mk2_7', label = 'クラシックアース色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用クラシックアース色' },
    weapontint_mk2_8             = { name = 'weapontint_mk2_8', label = 'クラシックブラウン＆ブラック色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用クラシックブラウン＆ブラック色' },
    weapontint_mk2_9             = { name = 'weapontint_mk2_9', label = 'レッドコントラスト色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用レッドコントラスト色' },
    weapontint_mk2_10            = { name = 'weapontint_mk2_10', label = 'ブルーコントラスト色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ブルーコントラスト色' },
    weapontint_mk2_11            = { name = 'weapontint_mk2_11', label = 'イエローコントラスト色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用イエローコントラスト色' },
    weapontint_mk2_12            = { name = 'weapontint_mk2_12', label = 'オレンジコントラスト色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用オレンジコントラスト色' },
    weapontint_mk2_13            = { name = 'weapontint_mk2_13', label = 'ボールドピンク色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドピンク色' },
    weapontint_mk2_14            = { name = 'weapontint_mk2_14', label = 'ボールドパープル＆イエロー色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドパープル＆イエロー色' },
    weapontint_mk2_15            = { name = 'weapontint_mk2_15', label = 'ボールドオレンジ色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドオレンジ色' },
    weapontint_mk2_16            = { name = 'weapontint_mk2_16', label = 'ボールドグリーン＆パープル色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドグリーン＆パープル色' },
    weapontint_mk2_17            = { name = 'weapontint_mk2_17', label = 'ボールドレッドフィーチャーズ色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドレッドフィーチャーズ色' },
    weapontint_mk2_18            = { name = 'weapontint_mk2_18', label = 'ボールドグリーンフィーチャーズ色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドグリーンフィーチャーズ色' },
    weapontint_mk2_19            = { name = 'weapontint_mk2_19', label = 'ボールドシアンフィーチャーズ色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドシアンフィーチャーズ色' },
    weapontint_mk2_20            = { name = 'weapontint_mk2_20', label = 'ボールドイエローフィーチャーズ色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドイエローフィーチャーズ色' },
    weapontint_mk2_21            = { name = 'weapontint_mk2_21', label = 'ボールドレッド＆ホワイト色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドレッド＆ホワイト色' },
    weapontint_mk2_22            = { name = 'weapontint_mk2_22', label = 'ボールドブルー＆ホワイト色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用ボールドブルー＆ホワイト色' },
    weapontint_mk2_23            = { name = 'weapontint_mk2_23', label = 'メタリックゴールド色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックゴールド色' },
    weapontint_mk2_24            = { name = 'weapontint_mk2_24', label = 'メタリックプラチナ色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックプラチナ色' },
    weapontint_mk2_25            = { name = 'weapontint_mk2_25', label = 'メタリックグレー＆ライラック色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックグレー＆ライラック色' },
    weapontint_mk2_26            = { name = 'weapontint_mk2_26', label = 'メタリックパープル＆ライム色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックパープル＆ライム色' },
    weapontint_mk2_27            = { name = 'weapontint_mk2_27', label = 'メタリックレッド色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックレッド色' },
    weapontint_mk2_28            = { name = 'weapontint_mk2_28', label = 'メタリックグリーン色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックグリーン色' },
    weapontint_mk2_29            = { name = 'weapontint_mk2_29', label = 'メタリックブルー色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックブルー色' },
    weapontint_mk2_30            = { name = 'weapontint_mk2_30', label = 'メタリックホワイト＆アクア色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックホワイト＆アクア色' },
    weapontint_mk2_31            = { name = 'weapontint_mk2_31', label = 'メタリックオレンジ＆イエロー色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックオレンジ＆イエロー色' },
    weapontint_mk2_32            = { name = 'weapontint_mk2_32', label = 'メタリックレッド＆イエロー色', weight = 1000, type = 'item', image = 'weapontint_black.png', unique = false, useable = true, shouldClose = true, description = 'MK2武器用メタリックレッド＆イエロー色' },

    -- アイテム
    -- 弾薬アイテム
    pistol_ammo                  = { name = 'pistol_ammo', label = 'ピストル弾薬', weight = 200, type = 'item', image = 'pistol_ammo.png', unique = false, useable = true, shouldClose = true, description = 'ピストル用の弾薬' },
    rifle_ammo                   = { name = 'rifle_ammo', label = 'ライフル弾薬', weight = 1000, type = 'item', image = 'rifle_ammo.png', unique = false, useable = true, shouldClose = true, description = 'ライフル用の弾薬' },
    smg_ammo                     = { name = 'smg_ammo', label = 'SMG弾薬', weight = 500, type = 'item', image = 'smg_ammo.png', unique = false, useable = true, shouldClose = true, description = 'サブマシンガン用の弾薬' },
    shotgun_ammo                 = { name = 'shotgun_ammo', label = 'ショットガン弾薬', weight = 500, type = 'item', image = 'shotgun_ammo.png', unique = false, useable = true, shouldClose = true, description = 'ショットガン用の弾薬' },
    mg_ammo                      = { name = 'mg_ammo', label = 'MG弾薬', weight = 1000, type = 'item', image = 'mg_ammo.png', unique = false, useable = true, shouldClose = true, description = 'マシンガン用の弾薬' },
    snp_ammo                     = { name = 'snp_ammo', label = 'スナイパー弾薬', weight = 1000, type = 'item', image = 'rifle_ammo.png', unique = false, useable = true, shouldClose = true, description = 'スナイパーライフル用の弾薬' },
    emp_ammo                     = { name = 'emp_ammo', label = 'EMP弾薬', weight = 200, type = 'item', image = 'emp_ammo.png', unique = false, useable = true, shouldClose = true, description = 'EMPランチャー用の弾薬' },

    -- カードアイテム
    id_card                      = { name = 'id_card', label = 'IDカード', weight = 0, type = 'item', image = 'id_card.png', unique = true, useable = true, shouldClose = false, description = '自分の情報をすべて含む身分証明書' },
    driver_license               = { name = 'driver_license', label = '運転免許証', weight = 0, type = 'item', image = 'driver_license.png', unique = true, useable = true, shouldClose = false, description = '車両を運転できることを示す許可証' },
    lawyerpass                   = { name = 'lawyerpass', label = '弁護士パス', weight = 0, type = 'item', image = 'lawyerpass.png', unique = true, useable = true, shouldClose = false, description = '弁護士のみが被疑者を弁護できることを示すパス' },
    weaponlicense                = { name = 'weaponlicense', label = '武器ライセンス', weight = 0, type = 'item', image = 'weapon_license.png', unique = true, useable = true, shouldClose = true, description = '武器ライセンス' },
    bank_card                    = { name = 'bank_card', label = '銀行カード', weight = 0, type = 'item', image = 'bank_card.png', unique = true, useable = true, shouldClose = true, description = 'ATMにアクセスするために使用する' },
    security_card_01             = { name = 'security_card_01', label = 'セキュリティカードA', weight = 0, type = 'item', image = 'security_card_01.png', unique = false, useable = true, shouldClose = true, description = 'セキュリティカード...どこに使うんだろう？' },
    security_card_02             = { name = 'security_card_02', label = 'セキュリティカードB', weight = 0, type = 'item', image = 'security_card_02.png', unique = false, useable = true, shouldClose = true, description = 'セキュリティカード...どこに使うんだろう？' },

    -- 食べるアイテム
    tosti                        = { name = 'tosti', label = 'グリルドチーズサンドイッチ', weight = 200, type = 'item', image = 'tosti.png', unique = false, useable = true, shouldClose = true, description = '食べると美味しい' },
    twerks_candy                 = { name = 'twerks_candy', label = 'トワークス', weight = 100, type = 'item', image = 'twerks_candy.png', unique = false, useable = true, shouldClose = true, description = '美味しいキャンディー :O' },
    snikkel_candy                = { name = 'snikkel_candy', label = 'スニッケル', weight = 100, type = 'item', image = 'snikkel_candy.png', unique = false, useable = true, shouldClose = true, description = '美味しいキャンディー :O' },
    sandwich                     = { name = 'sandwich', label = 'サンドイッチ', weight = 200, type = 'item', image = 'sandwich.png', unique = false, useable = true, shouldClose = true, description = 'お腹に優しいパン' },

    -- 飲むアイテム
    water_bottle                 = { name = 'water_bottle', label = '水のボトル', weight = 500, type = 'item', image = 'water_bottle.png', unique = false, useable = true, shouldClose = true, description = '喉が渇いている人みんなに' },
    coffee                       = { name = 'coffee', label = 'コーヒー', weight = 200, type = 'item', image = 'coffee.png', unique = false, useable = true, shouldClose = true, description = 'カフェイン補給' },
    kurkakola                    = { name = 'kurkakola', label = 'コーラ', weight = 500, type = 'item', image = 'cola.png', unique = false, useable = true, shouldClose = true, description = '喉が渇いている人みんなに' },

    -- アルコール
    beer                         = { name = 'beer', label = 'ビール', weight = 500, type = 'item', image = 'beer.png', unique = false, useable = true, shouldClose = true, description = '冷えた美味しいビールに勝るものはない！' },
    whiskey                      = { name = 'whiskey', label = 'ウィスキー', weight = 500, type = 'item', image = 'whiskey.png', unique = false, useable = true, shouldClose = true, description = '喉が渇いている人みんなに' },
    vodka                        = { name = 'vodka', label = 'ウォッカ', weight = 500, type = 'item', image = 'vodka.png', unique = false, useable = true, shouldClose = true, description = '喉が渇いている人みんなに' },
    grape                        = { name = 'grape', label = 'ブドウ', weight = 100, type = 'item', image = 'grape.png', unique = false, useable = true, shouldClose = false, description = 'うーん、美味しいブドウ' },
    wine                         = { name = 'wine', label = 'ワイン', weight = 300, type = 'item', image = 'wine.png', unique = false, useable = true, shouldClose = false, description = '素敵な夜に飲む良いワイン' },
    grapejuice                   = { name = 'grapejuice', label = 'ブドウジュース', weight = 200, type = 'item', image = 'grapejuice.png', unique = false, useable = true, shouldClose = false, description = 'ブドウジュースは健康に良いと言われている' },

    -- ドラッグ
    joint                        = { name = 'joint', label = 'ジョイント', weight = 0, type = 'item', image = 'joint.png', unique = false, useable = true, shouldClose = true, description = 'シドニーは君をとても誇りに思うだろう' },
    cokebaggy                    = { name = 'cokebaggy', label = 'コカインの袋', weight = 0, type = 'item', image = 'cocaine_baggy.png', unique = false, useable = true, shouldClose = true, description = 'すぐに幸せになるために' },
    crack_baggy                  = { name = 'crack_baggy', label = 'クラックの袋', weight = 0, type = 'item', image = 'crack_baggy.png', unique = false, useable = true, shouldClose = true, description = 'もっと早く幸せになるために' },
    xtcbaggy                     = { name = 'xtcbaggy', label = 'XTCの袋', weight = 0, type = 'item', image = 'xtc_baggy.png', unique = false, useable = true, shouldClose = true, description = 'その錠剤をポップしようぜ、ベイビー' },
    coke_brick                   = { name = 'coke_brick', label = 'コカインのブロック', weight = 1000, type = 'item', image = 'coke_brick.png', unique = true, useable = false, shouldClose = true, description = 'コカインの重いパッケージ。主に取引に使われ、かなりのスペースを取る' },
    weed_brick                   = { name = 'weed_brick', label = 'マリファナのブロック', weight = 1000, type = 'item', image = 'weed_brick.png', unique = false, useable = false, shouldClose = true, description = '大口顧客に売るための1KGのマリファナブロック' },
    coke_small_brick             = { name = 'coke_small_brick', label = 'コカインのパッケージ', weight = 350, type = 'item', image = 'coke_small_brick.png', unique = true, useable = false, shouldClose = true, description = 'コカインの小さなパッケージ。主に取引に使われ、かなりのスペースを取る' },
    oxy                          = { name = 'oxy', label = '処方箋オキシコドン', weight = 0, type = 'item', image = 'oxy.png', unique = false, useable = true, shouldClose = true, description = 'ラベルは剥がされている' },
    meth                         = { name = 'meth', label = 'メス', weight = 100, type = 'item', image = 'meth_baggy.png', unique = false, useable = true, shouldClose = true, description = 'メスの小袋' },
    rolling_paper                = { name = 'rolling_paper', label = '巻き紙', weight = 0, type = 'item', image = 'rolling_paper.png', unique = false, useable = false, shouldClose = true, description = 'タバコや大麻を包んで喫煙するために特別に作られた紙' },

    -- 種とマリファナ
    weed_whitewidow              = { name = 'weed_whitewidow', label = 'ホワイトウィドウ 2g', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = 'ホワイトウィドウ 2g入りのマリファナバッグ' },
    weed_skunk                   = { name = 'weed_skunk', label = 'スカンク 2g', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = 'スカンク 2g入りのマリファナバッグ' },
    weed_purplehaze              = { name = 'weed_purplehaze', label = 'パープルヘイズ 2g', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = 'パープルヘイズ 2g入りのマリファナバッグ' },
    weed_ogkush                  = { name = 'weed_ogkush', label = 'OGクッシュ 2g', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = 'OGクッシュ 2g入りのマリファナバッグ' },
    weed_amnesia                 = { name = 'weed_amnesia', label = 'アムネシア 2g', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = 'アムネシア 2g入りのマリファナバッグ' },
    weed_ak47                    = { name = 'weed_ak47', label = 'AK47 2g', weight = 200, type = 'item', image = 'weed_baggy.png', unique = false, useable = true, shouldClose = false, description = 'AK47 2g入りのマリファナバッグ' },
    weed_whitewidow_seed         = { name = 'weed_whitewidow_seed', label = 'ホワイトウィドウの種', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = false, description = 'ホワイトウィドウのマリファナの種' },
    weed_skunk_seed              = { name = 'weed_skunk_seed', label = 'スカンクの種', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = 'スカンクのマリファナの種' },
    weed_purplehaze_seed         = { name = 'weed_purplehaze_seed', label = 'パープルヘイズの種', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = 'パープルヘイズのマリファナの種' },
    weed_ogkush_seed             = { name = 'weed_ogkush_seed', label = 'OGクッシュの種', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = 'OGクッシュのマリファナの種' },
    weed_amnesia_seed            = { name = 'weed_amnesia_seed', label = 'アムネシアの種', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = 'アムネシアのマリファナの種' },
    weed_ak47_seed               = { name = 'weed_ak47_seed', label = 'AK47の種', weight = 0, type = 'item', image = 'weed_seed.png', unique = false, useable = true, shouldClose = true, description = 'AK47のマリファナの種' },
    empty_weed_bag               = { name = 'empty_weed_bag', label = '空のマリファナバッグ', weight = 0, type = 'item', image = 'weed_baggy_empty.png', unique = false, useable = true, shouldClose = true, description = '小さな空の袋' },
    weed_nutrition               = { name = 'weed_nutrition', label = '植物肥料', weight = 2000, type = 'item', image = 'weed_nutrition.png', unique = false, useable = true, shouldClose = true, description = '植物の栄養' },

    -- 素材
    plastic                      = { name = 'plastic', label = 'プラスチック', weight = 100, type = 'item', image = 'plastic.png', unique = false, useable = false, shouldClose = false, description = 'リサイクル！ - グレタ・トゥーンベリ 2019' },
    metalscrap                   = { name = 'metalscrap', label = '金属くず', weight = 100, type = 'item', image = 'metalscrap.png', unique = false, useable = false, shouldClose = false, description = 'これを使って何か素敵なものを作れるかもしれない' },
    copper                       = { name = 'copper', label = '銅', weight = 100, type = 'item', image = 'copper.png', unique = false, useable = false, shouldClose = false, description = '何かに使えるかもしれない、素敵な金属の塊' },
    aluminum                     = { name = 'aluminum', label = 'アルミニウム', weight = 100, type = 'item', image = 'aluminum.png', unique = false, useable = false, shouldClose = false, description = '何かに使えるかもしれない、素敵な金属の塊' },
    aluminumoxide                = { name = 'aluminumoxide', label = 'アルミニウムパウダー', weight = 100, type = 'item', image = 'aluminumoxide.png', unique = false, useable = false, shouldClose = false, description = '混ぜるためのパウダー' },
    iron                         = { name = 'iron', label = '鉄', weight = 100, type = 'item', image = 'iron.png', unique = false, useable = false, shouldClose = false, description = '何かに使えるかもしれない、便利な金属の塊' },
    ironoxide                    = { name = 'ironoxide', label = '鉄パウダー', weight = 100, type = 'item', image = 'ironoxide.png', unique = false, useable = false, shouldClose = false, description = '混ぜるためのパウダー' },
    steel                        = { name = 'steel', label = 'スチール', weight = 100, type = 'item', image = 'steel.png', unique = false, useable = false, shouldClose = false, description = '何かに使えるかもしれない、素敵な金属の塊' },
    rubber                       = { name = 'rubber', label = 'ゴム', weight = 100, type = 'item', image = 'rubber.png', unique = false, useable = false, shouldClose = false, description = 'ゴム。これを使って自分だけのゴム製アヒルを作れると思うよ :D' },
    glass                        = { name = 'glass', label = 'ガラス', weight = 100, type = 'item', image = 'glass.png', unique = false, useable = false, shouldClose = false, description = 'とても壊れやすいから、注意して' },

    -- ツール
    lockpick                     = { name = 'lockpick', label = '鍵開けツール', weight = 300, type = 'item', image = 'lockpick.png', unique = false, useable = true, shouldClose = true, description = '鍵をよくなくす人にはとても便利... あるいは、他の何かに使うこともできる...' },
    advancedlockpick             = { name = 'advancedlockpick', label = '高度な鍵開けツール', weight = 500, type = 'item', image = 'advancedlockpick.png', unique = false, useable = true, shouldClose = true, description = '鍵をよくなくす人にはとても便利... ビールを開けるのにも便利' },
    electronickit                = { name = 'electronickit', label = '電子キット', weight = 100, type = 'item', image = 'electronickit.png', unique = false, useable = true, shouldClose = true, description = 'ずっとロボットを作りたかったなら、ここから始められるかも。新しいイーロン・マスクになるかも？' },
    gatecrack                    = { name = 'gatecrack', label = 'ゲートクラック', weight = 0, type = 'item', image = 'usb_device.png', unique = false, useable = false, shouldClose = true, description = 'いくつかのフェンスを破壊するための便利なソフトウェア' },
    thermite                     = { name = 'thermite', label = 'テルミット', weight = 1000, type = 'item', image = 'thermite.png', unique = false, useable = true, shouldClose = true, description = 'すべて燃えてしまえばいいと思う時もあるだろう' },
    trojan_usb                   = { name = 'trojan_usb', label = 'トロイの木馬USB', weight = 0, type = 'item', image = 'usb_device.png', unique = false, useable = false, shouldClose = true, description = 'いくつかのシステムをシャットダウンするための便利なソフトウェア' },
    screwdriverset               = { name = 'screwdriverset', label = 'ツールキット', weight = 1000, type = 'item', image = 'screwdriverset.png', unique = false, useable = false, shouldClose = false, description = 'ネジを...回すのにとても便利...' },
    drill                        = { name = 'drill', label = 'ドリル', weight = 20000, type = 'item', image = 'drill.png', unique = false, useable = false, shouldClose = false, description = '本物だ...' },

    -- 車両ツール
    nitrous                      = { name = 'nitrous', label = 'ナイトラス', weight = 1000, type = 'item', image = 'nitrous.png', unique = false, useable = true, shouldClose = true, description = 'スピードアップ、アクセル全開！ :D' },
    repairkit                    = { name = 'repairkit', label = '修理キット', weight = 2500, type = 'item', image = 'repairkit.png', unique = false, useable = true, shouldClose = true, description = '車両を修理するための道具が入った素敵なツールボックス' },
    advancedrepairkit            = { name = 'advancedrepairkit', label = '高度な修理キット', weight = 4000, type = 'item', image = 'advancedkit.png', unique = false, useable = true, shouldClose = true, description = '車両を修理するための道具が入った素敵なツールボックス' },
    cleaningkit                  = { name = 'cleaningkit', label = 'クリーニングキット', weight = 250, type = 'item', image = 'cleaningkit.png', unique = false, useable = true, shouldClose = true, description = 'マイクロファイバークロスと石鹸で、あなたの車は再び輝きます！' },
    tunerlaptop                  = { name = 'tunerlaptop', label = 'チューナーチップ', weight = 2000, type = 'item', image = 'tunerchip.png', unique = true, useable = true, shouldClose = true, description = 'このチューナーチップを使えば、車をドーピングできる... もしやり方を知っていればだけど' },
    harness                      = { name = 'harness', label = 'レースハーネス', weight = 1000, type = 'item', image = 'harness.png', unique = true, useable = true, shouldClose = true, description = 'どんなことがあっても車から落ちないようにするためのレースハーネス' },
    jerry_can                    = { name = 'jerry_can', label = 'ガソリン缶 20L', weight = 20000, type = 'item', image = 'jerry_can.png', unique = false, useable = true, shouldClose = true, description = '燃料でいっぱいの缶' },
    tirerepairkit                = { name = 'tirerepairkit', label = 'タイヤ修理キット', weight = 1000, type = 'item', image = 'tirerepairkit.png', unique = false, useable = true, shouldClose = true, description = 'タイヤを修理するためのキット' },

    -- メカニックパーツ
    veh_toolbox                  = { name = 'veh_toolbox', label = 'ツールボックス', weight = 1000, type = 'item', image = 'veh_toolbox.png', unique = false, useable = true, shouldClose = true, description = '車両の状態をチェック' },
    veh_armor                    = { name = 'veh_armor', label = 'アーマー', weight = 1000, type = 'item', image = 'veh_armor.png', unique = false, useable = true, shouldClose = true, description = '車両のアーマーをアップグレード' },
    veh_brakes                   = { name = 'veh_brakes', label = 'ブレーキ', weight = 1000, type = 'item', image = 'veh_brakes.png', unique = false, useable = true, shouldClose = true, description = '車両のブレーキをアップグレード' },
    veh_engine                   = { name = 'veh_engine', label = 'エンジン', weight = 1000, type = 'item', image = 'veh_engine.png', unique = false, useable = true, shouldClose = true, description = '車両のエンジンをアップグレード' },
    veh_suspension               = { name = 'veh_suspension', label = 'サスペンション', weight = 1000, type = 'item', image = 'veh_suspension.png', unique = false, useable = true, shouldClose = true, description = '車両のサスペンションをアップグレード' },
    veh_transmission             = { name = 'veh_transmission', label = 'トランスミッション', weight = 1000, type = 'item', image = 'veh_transmission.png', unique = false, useable = true, shouldClose = true, description = '車両のトランスミッションをアップグレード' },
    veh_turbo                    = { name = 'veh_turbo', label = 'ターボ', weight = 1000, type = 'item', image = 'veh_turbo.png', unique = false, useable = true, shouldClose = true, description = '車両にターボをインストール' },
    veh_interior                 = { name = 'veh_interior', label = 'インテリア', weight = 1000, type = 'item', image = 'veh_interior.png', unique = false, useable = true, shouldClose = true, description = '車両のインテリアをアップグレード' },
    veh_exterior                 = { name = 'veh_exterior', label = 'エクステリア', weight = 1000, type = 'item', image = 'veh_exterior.png', unique = false, useable = true, shouldClose = true, description = '車両のエクステリアをアップグレード' },
    veh_wheels                   = { name = 'veh_wheels', label = 'ホイール', weight = 1000, type = 'item', image = 'veh_wheels.png', unique = false, useable = true, shouldClose = true, description = '車両のホイールをアップグレード' },
    veh_neons                    = { name = 'veh_neons', label = 'ネオン', weight = 1000, type = 'item', image = 'veh_neons.png', unique = false, useable = true, shouldClose = true, description = '車両のネオンをアップグレード' },
    veh_xenons                   = { name = 'veh_xenons', label = 'キセノン', weight = 1000, type = 'item', image = 'veh_xenons.png', unique = false, useable = true, shouldClose = true, description = '車両のキセノンをアップグレード' },
    veh_tint                     = { name = 'veh_tint', label = 'ウィンドウフィルム', weight = 1000, type = 'item', image = 'veh_tint.png', unique = false, useable = true, shouldClose = true, description = '車両にウィンドウフィルムをインストール' },
    veh_plates                   = { name = 'veh_plates', label = 'ナンバープレート', weight = 1000, type = 'item', image = 'veh_plates.png', unique = false, useable = true, shouldClose = true, description = '車両にナンバープレートをインストール' },

    -- 医薬品
    firstaid                     = { name = 'firstaid', label = '救急セット', weight = 2500, type = 'item', image = 'firstaid.png', unique = false, useable = true, shouldClose = true, description = 'この救急セットを使って人々を元気にすることができる' },
    bandage                      = { name = 'bandage', label = '包帯', weight = 0, type = 'item', image = 'bandage.png', unique = false, useable = true, shouldClose = true, description = '包帯はいつでも効く' },
    ifaks                        = { name = 'ifaks', label = 'IFAKS', weight = 200, type = 'item', image = 'ifaks.png', unique = false, useable = true, shouldClose = true, description = '治癒と完全なストレス解消のためのIFAKS' },
    painkillers                  = { name = 'painkillers', label = '鎮痛剤', weight = 0, type = 'item', image = 'painkillers.png', unique = false, useable = true, shouldClose = true, description = '耐えられない痛みのために、この錠剤を飲めば再び気分が良くなるだろう' },
    walkstick                    = { name = 'walkstick', label = 'ステッキ', weight = 1000, type = 'item', image = 'walkstick.png', unique = false, useable = true, shouldClose = true, description = 'そこにいるおばあちゃんたちのためのステッキ... HAHA' },

    -- 通信
    phone                        = { name = 'phone', label = '電話', weight = 700, type = 'item', image = 'phone.png', unique = true, useable = false, shouldClose = false, description = 'きちんとした電話だね' },
    radio                        = { name = 'radio', label = 'ラジオ', weight = 2000, type = 'item', image = 'radio.png', unique = true, useable = true, shouldClose = true, description = 'これを使って信号で通信できる' },
    iphone                       = { name = 'iphone', label = 'iphone', weight = 1000, type = 'item', image = 'iphone.png', unique = false, useable = false, shouldClose = true, description = 'リンゴが描かれたスマートフォン' },
    samsungphone                 = { name = 'samsungphone', label = 'Samsung S10', weight = 1000, type = 'item', image = 'samsungphone.png', unique = false, useable = false, shouldClose = true, description = 'スリムで使いやすいスマートフォン' },
    laptop                       = { name = 'laptop', label = 'ノートパソコン', weight = 4000, type = 'item', image = 'laptop.png', unique = false, useable = false, shouldClose = true, description = '高価なノートパソコン' },
    tablet                       = { name = 'tablet', label = 'タブレット', weight = 2000, type = 'item', image = 'tablet.png', unique = false, useable = false, shouldClose = true, description = '高価なタブレット' },
    fitbit                       = { name = 'fitbit', label = 'フィットビット', weight = 500, type = 'item', image = 'fitbit.png', unique = true, useable = true, shouldClose = true, description = 'フィットビットは好きだよ' },
    radioscanner                 = { name = 'radioscanner', label = '無線スキャナー', weight = 1000, type = 'item', image = 'radioscanner.png', unique = false, useable = false, shouldClose = true, description = 'これで警察の警報を受け取ることができる。しかし、100%効果的ではない' },
    pinger                       = { name = 'pinger', label = 'ピンガー', weight = 1000, type = 'item', image = 'pinger.png', unique = false, useable = false, shouldClose = true, description = 'ピンガーと電話があれば、自分の位置情報を送信できる' },
    cryptostick                  = { name = 'cryptostick', label = '暗号スティック', weight = 200, type = 'item', image = 'cryptostick.png', unique = true, useable = true, shouldClose = true, description = 'なぜ誰も存在しないお金を買うんだろう... どれくらい入ってるんだろう...？' },

    -- 盗品と宝石
    rolex                        = { name = 'rolex', label = '金の腕時計', weight = 1500, type = 'item', image = 'rolex.png', unique = false, useable = false, shouldClose = true, description = '金の腕時計は私にとって大当たりに見える！' },
    diamond_ring                 = { name = 'diamond_ring', label = 'ダイヤモンドリング', weight = 1500, type = 'item', image = 'diamond_ring.png', unique = false, useable = false, shouldClose = true, description = 'ダイヤモンドリングは私にとって大当たりに見える！' },
    diamond                      = { name = 'diamond', label = 'ダイヤモンド', weight = 1000, type = 'item', image = 'diamond.png', unique = false, useable = false, shouldClose = true, description = 'ダイヤモンドは私にとって大当たりに見える！' },
    goldchain                    = { name = 'goldchain', label = '金のチェーン', weight = 1500, type = 'item', image = 'goldchain.png', unique = false, useable = false, shouldClose = true, description = '金のチェーンは私にとって大当たりに見える！' },
    tenkgoldchain                = { name = 'tenkgoldchain', label = '10k金のチェーン', weight = 2000, type = 'item', image = '10kgoldchain.png', unique = false, useable = false, shouldClose = true, description = '10カラットの金のチェーン' },
    goldbar                      = { name = 'goldbar', label = '金の延べ棒', weight = 7000, type = 'item', image = 'goldbar.png', unique = false, useable = false, shouldClose = true, description = 'かなり高価そうに見える' },

    -- 警察ツール
    armor                        = { name = 'armor', label = 'アーマー', weight = 5000, type = 'item', image = 'armor.png', unique = false, useable = true, shouldClose = true, description = '少しの保護は悪くない...だろ？' },
    heavyarmor                   = { name = 'heavyarmor', label = '重装アーマー', weight = 5000, type = 'item', image = 'armor.png', unique = false, useable = true, shouldClose = true, description = '少しの保護は悪くない...だろ？' },
    handcuffs                    = { name = 'handcuffs', label = '手錠', weight = 100, type = 'item', image = 'handcuffs.png', unique = false, useable = true, shouldClose = true, description = '人々が悪い振る舞いをしたときに便利。他の何かに使うこともできるかも？' },
    police_stormram              = { name = 'police_stormram', label = '突入用ハンマー', weight = 18000, type = 'item', image = 'police_stormram.png', unique = false, useable = true, shouldClose = true, description = 'ドアをこじ開けるのに便利なツール' },
    empty_evidence_bag           = { name = 'empty_evidence_bag', label = '空の証拠品バッグ', weight = 0, type = 'item', image = 'evidence.png', unique = false, useable = false, shouldClose = false, description = '血液、薬莢などからDNAを保管するために頻繁に使用される' },
    filled_evidence_bag          = { name = 'filled_evidence_bag', label = '証拠品バッグ', weight = 200, type = 'item', image = 'evidence.png', unique = true, useable = false, shouldClose = false, description = '誰が犯罪を犯したかを知るための、中身の入った証拠品バッグ >:(' },

    -- 花火ツール
    firework1                    = { name = 'firework1', label = '2ブラザーズ', weight = 1000, type = 'item', image = 'firework1.png', unique = false, useable = true, shouldClose = true, description = '花火' },
    firework2                    = { name = 'firework2', label = 'ポッペラーズ', weight = 1000, type = 'item', image = 'firework2.png', unique = false, useable = true, shouldClose = true, description = '花火' },
    firework3                    = { name = 'firework3', label = 'ワイプアウト', weight = 1000, type = 'item', image = 'firework3.png', unique = false, useable = true, shouldClose = true, description = '花火' },
    firework4                    = { name = 'firework4', label = 'ウィーピングウィロー', weight = 1000, type = 'item', image = 'firework4.png', unique = false, useable = true, shouldClose = true, description = '花火' },

    -- 海洋ツール
    dendrogyra_coral             = { name = 'dendrogyra_coral', label = 'デンロジラサンゴ', weight = 1000, type = 'item', image = 'dendrogyra_coral.png', unique = false, useable = false, shouldClose = true, description = '柱状サンゴとしても知られている' },
    antipatharia_coral           = { name = 'antipatharia_coral', label = 'アンティパタリアサンゴ', weight = 1000, type = 'item', image = 'antipatharia_coral.png', unique = false, useable = false, shouldClose = true, description = 'ブラックサンゴやソーンサンゴとしても知られている' },
    diving_gear                  = { name = 'diving_gear', label = 'ダイビングギア', weight = 30000, type = 'item', image = 'diving_gear.png', unique = true, useable = true, shouldClose = true, description = '酸素ボンベとリブリーザー' },
    diving_fill                  = { name = 'diving_fill', label = 'ダイビングチューブ', weight = 3000, type = 'item', image = 'diving_tube.png', unique = true, useable = true, shouldClose = true, description = '酸素チューブとリブリーザー' },

    -- Other Tools
    casinochips                  = { name = 'casinochips', label = 'Casino Chips', weight = 0, type = 'item', image = 'casinochips.png', unique = false, useable = false, shouldClose = false, description = 'Chips For Casino Gambling' },
    stickynote                   = { name = 'stickynote', label = 'Sticky note', weight = 0, type = 'item', image = 'stickynote.png', unique = true, useable = false, shouldClose = false, description = 'Sometimes handy to remember something :)' },
    wheeltoken                   = { name = 'wheeltoken', label = 'Lucky Wheel Token', weight = 100, type = 'item', image = 'token.png', unique = false, useable = false, shouldClose = false, description = 'Lucky Wheel Token', expire = 9 },
    moneybag                     = { name = 'moneybag', label = 'Money Bag', weight = 0, type = 'item', image = 'moneybag.png', unique = true, useable = true, shouldClose = true, description = 'A bag with cash' },
    parachute                    = { name = 'parachute', label = 'Parachute', weight = 30000, type = 'item', image = 'parachute.png', unique = true, useable = true, shouldClose = true, description = 'The sky is the limit! Woohoo!' },
    binoculars                   = { name = 'binoculars', label = 'Binoculars', weight = 600, type = 'item', image = 'binoculars.png', unique = false, useable = true, shouldClose = true, description = 'Sneaky Breaky...' },
    lighter                      = { name = 'lighter', label = 'Lighter', weight = 0, type = 'item', image = 'lighter.png', unique = false, useable = false, shouldClose = true, description = 'On new years eve a nice fire to stand next to' },
    certificate                  = { name = 'certificate', label = 'Certificate', weight = 0, type = 'item', image = 'certificate.png', unique = false, useable = false, shouldClose = true, description = 'Certificate that proves you own certain stuff' },
    markedbills                  = { name = 'markedbills', label = 'Marked Money', weight = 1000, type = 'item', image = 'markedbills.png', unique = true, useable = false, shouldClose = true, description = 'Money?' },
    labkey                       = { name = 'labkey', label = 'Key', weight = 500, type = 'item', image = 'labkey.png', unique = true, useable = true, shouldClose = true, description = 'Key for a lock...?' },
    printerdocument              = { name = 'printerdocument', label = 'Document', weight = 500, type = 'item', image = 'printerdocument.png', unique = true, useable = true, shouldClose = true, description = 'A nice document' },
    newscam                      = { name = 'newscam', label = 'News Camera', weight = 100, type = 'item', image = 'newscam.png', unique = true, useable = true, shouldClose = true, description = 'A camera for the news' },
    newsmic                      = { name = 'newsmic', label = 'News Microphone', weight = 100, type = 'item', image = 'newsmic.png', unique = true, useable = true, shouldClose = true, description = 'A microphone for the news' },
    newsbmic                     = { name = 'newsbmic', label = 'Boom Microphone', weight = 100, type = 'item', image = 'newsbmic.png', unique = true, useable = true, shouldClose = true, description = 'A Useable BoomMic' },
    -- その他のツール
    casinochips                  = { name = 'casinochips', label = 'カジノチップ', weight = 0, type = 'item', image = 'casinochips.png', unique = false, useable = false, shouldClose = false, description = 'カジノのギャンブル用チップ' },
    stickynote                   = { name = 'stickynote', label = '付箋', weight = 0, type = 'item', image = 'stickynote.png', unique = true, useable = false, shouldClose = false, description = '何かを覚えておくのに便利 :)' },
    moneybag                     = { name = 'moneybag', label = '現金バッグ', weight = 0, type = 'item', image = 'moneybag.png', unique = true, useable = true, shouldClose = true, description = '現金が入ったバッグ' },
    parachute                    = { name = 'parachute', label = 'パラシュート', weight = 30000, type = 'item', image = 'parachute.png', unique = true, useable = true, shouldClose = true, description = '空が限界！イェーイ！' },
    binoculars                   = { name = 'binoculars', label = '双眼鏡', weight = 600, type = 'item', image = 'binoculars.png', unique = false, useable = true, shouldClose = true, description = 'コソコソ...' },
    lighter                      = { name = 'lighter', label = 'ライター', weight = 0, type = 'item', image = 'lighter.png', unique = false, useable = false, shouldClose = true, description = '大晦日に横で暖をとるのに良い火' },
    certificate                  = { name = 'certificate', label = '証明書', weight = 0, type = 'item', image = 'certificate.png', unique = false, useable = false, shouldClose = true, description = '特定のものを所有していることを証明する証明書' },
    markedbills                  = { name = 'markedbills', label = 'マーク付きの紙幣', weight = 1000, type = 'item', image = 'markedbills.png', unique = true, useable = false, shouldClose = true, description = 'お金？' },
    labkey                       = { name = 'labkey', label = '鍵', weight = 500, type = 'item', image = 'labkey.png', unique = true, useable = true, shouldClose = true, description = '鍵を開けるための鍵...？' },
    printerdocument              = { name = 'printerdocument', label = '書類', weight = 500, type = 'item', image = 'printerdocument.png', unique = true, useable = true, shouldClose = true, description = '良い書類' },
    newscam                      = { name = 'newscam', label = 'ニュースカメラ', weight = 100, type = 'item', image = 'newscam.png', unique = true, useable = true, shouldClose = true, description = 'ニュース用カメラ' },
    newsmic                      = { name = 'newsmic', label = 'ニュースマイク', weight = 100, type = 'item', image = 'newsmic.png', unique = true, useable = true, shouldClose = true, description = 'ニュース用マイク' },
    newsbmic                     = { name = 'newsbmic', label = 'ブームマイク', weight = 100, type = 'item', image = 'newsbmic.png', unique = true, useable = true, shouldClose = true, description = '使用可能なブームマイク' },

    -- 木こり関連アイテム (2026.08.23 追加 potato)
    wood = {
        name = 'wood',
        label = '原木',
        weight = 1000,
        type = 'item',
        image = 'wood.png',
        unique = false,
        useable = false,
        shouldClose = false,
        combinable = nil,
        description = '伐採した未加工の木材'
    },

    wood_pro = {
        name = 'wood_pro',
        label = '加工済み木材',
        weight = 1000,
        type = 'item',
        image = 'wood_proc.png',
        unique = false,
        useable = false,
        shouldClose = false,
        combinable = nil,
        description = '加工され、販売できる状態になった木材'
    },

    -- クラフトテーブル
    item_bench = {name = "item_bench", label = "作業台", weight = 15000, type = "item", image = "workbench.png", unique = true, useable = true, shouldClose = false, combinable = nil, description = "アイテムを作成するための作業台。"},
    attachment_bench = {name = "attachment_bench", label = "アタッチメント作業台", weight = 15000, type = "item", image = "attworkbench.png", unique = true, useable = true, shouldClose = false, combinable = nil, description = "アタッチメントを作成するための作業台。"},

}